server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true # registers the service ip rather than the server name
  client:
    register-with-eureka: true # register him self at eureka
    fetch-registry: true # pull down a local copy of the registries
    service-url:
      defaultZone: http://localhost:8083/eureka # discovery service location

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true # use netflix eureka discovery service
jwt:
  secret: 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTYyODI0NDA0NCwiaWF0IjoxNjI4MjQ0MDQ0fQ.NLjdWWR4ZXAivy8_ukpgXfrp7-7A3AIhFr7DZhAg0Fw'